development:
  adapter: postgresql
  encoding: unicode
  database: taha-craigslist-developer
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: taha-craigslsit-product
  pool: 5
  url: <%=ENV['DATABASE_URL']%>