Category.create(name: 'Jobs')
Category.create(name: 'Services')
Category.create(name: 'Sale')

Subcategory.create(name: 'Web Developer', category_id: 1)
Subcategory.create(name: 'Accounting', category_id: 1)
Subcategory.create(name: 'Admin', category_id: 1)
Subcategory.create(name: 'Biotech', category_id: 1)
Subcategory.create(name: 'Customer Service', category_id: 1)
Subcategory.create(name: 'Waiter', category_id: 1)
Subcategory.create(name: 'Real State', category_id: 1)
Subcategory.create(name: 'Web Designer', category_id: 1)
Subcategory.create(name: 'Security', category_id: 1)

Subcategory.create(name: 'Web Development', category_id: 2)
Subcategory.create(name: 'Web Design', category_id: 2)
Subcategory.create(name: 'Beauty', category_id: 2)
Subcategory.create(name: 'Pet', category_id: 2)
Subcategory.create(name: 'Event', category_id: 2)
Subcategory.create(name: 'Financial', category_id: 2)
Subcategory.create(name: 'Household', category_id: 2)
Subcategory.create(name: 'Creative', category_id: 2)
Subcategory.create(name: 'Computer', category_id: 2)

Subcategory.create(name: 'Car', category_id: 3)
Subcategory.create(name: 'Toys', category_id: 3)
Subcategory.create(name: 'Jeverly', category_id: 3)
Subcategory.create(name: 'Materials', category_id: 3)
Subcategory.create(name: 'Bikes', category_id: 3)
Subcategory.create(name: 'Books', category_id: 3)
Subcategory.create(name: 'Business', category_id: 3)
Subcategory.create(name: 'Phones', category_id: 3)
Subcategory.create(name: 'Electronics', category_id: 3)
Subcategory.create(name: 'Clothes', category_id: 3)